## Authorizations
# Uncomment out the merging for each environment that you'd like to include.
# You can also just copy and paste the tree (do not include the "authorizations") to each
# environment if you need something different per environment.
authorizations: &AUTHORIZATIONS
  group_base: ou=people,o=unsw,dc=localhost
  ## Requires config.ldap_check_group_membership in devise.rb be true
  # Can have multiple values, must match all to be authorized
  required_groups:
    - cn=admins,ou=groups,dc=test,dc=com
    - cn=users,ou=groups,dc=test,dc=com
  ## Requires config.ldap_check_attributes in devise.rb to be true
  ## Can have multiple attributes and values, must match all to be authorized
  require_attribute:
    objectClass: inetOrgPerson

## Environments
common: &common
  host: localhost
  port: 389
  attribute: cn
  base: ou=people,o=unsw,dc=localhost
  admin_user: cn=admin,dc=localhost
  admin_password: Pass.123
  ssl: false

mock: &mock
  host: localhost
  port: 3897
  attribute: cn
  base: ou=people,dc=localhost
  admin_user: cn=admin,dc=localhost
  admin_password: cQmN7yTArff6cd9e9Ow4DLcHNYL7wLyK
  ssl: false

development:
  <<: *common

test:
  host: localhost
  port: 389
  attribute: cn
  base: ou=people,o=test,dc=localhost
  admin_user: cn=admin,dc=localhost
  admin_password: Pass.123
  ssl: false

qa:
  <<: *common

staging:
  <<: *common

production:
  host: ad.unsw.edu.au
  port: 389
  attribute: cn
  base: ou=IDM_People,ou=IDM,dc=ad,dc=unsw,dc=edu,dc=au
  admin_user: CN=svcENGCHERSCdata,OU=_Service Accounts,OU=Managed Windows,OU=Servers,DC=ad,DC=unsw,DC=edu,DC=au
  admin_password: O8fssSyD22ce2ePcBvJ5
  ssl: false
