common: &common
  host: deployment-tracker.intersect.org.au

# development:
#   host: localhost
#   port: 3001

qa: &qa
  <<: *common

qa2: &qa2
  <<: *common

staging:
  <<: *common

staging2:
  <<: *common

production:
  <<: *common
